#Cannot keep it empty otherwise it will throw error.
AUGMENTATION: True
IMAGE_SIZE: [224, 224, 3] # as per VGG 16 model(Got all of the params form keras official website)
BATCH_SIZE: 16
INCLUDE_TOP: False
EPOCHS: 1
CLASSES: 2
WEIGHTS: imagenet
LEARNING_RATE: 0.01